name: accounter
description: 家計簿
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  drift: ^2.8.0
  flutter:
    sdk: flutter
  path: ^1.8.3
  path_provider: ^2.0.15
  provider: ^6.0.5
  shimmer: ^2.0.0
  sqlite3_flutter_libs: ^0.5.14

dev_dependencies:
  build_runner: ^2.4.2
  drift_dev: ^2.8.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/fonts/ZenKakuGothicNew/
  fonts:
    - family: ZenKakuGothicNew
      fonts:
        - asset: assets/fonts/ZenKakuGothicNew/ZenKakuGothicNew-Light.ttf
          weight: 300
        - asset: assets/fonts/ZenKakuGothicNew/ZenKakuGothicNew-Regular.ttf
          weight: 400
        - asset: assets/fonts/ZenKakuGothicNew/ZenKakuGothicNew-Medium.ttf
          weight: 500
        - asset: assets/fonts/ZenKakuGothicNew/ZenKakuGothicNew-Bold.ttf
          weight: 700
        - asset: assets/fonts/ZenKakuGothicNew/ZenKakuGothicNew-Black.ttf
          weight: 900
  uses-material-design: true
