name: accounter
description: 家計簿
publish_to: "none"
version: 0.2.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  camera: ^0.10.5+2
  drift: ^2.8.0
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_expandable_fab: ^1.8.1
  flutter_hooks: ^0.18.6
  flutter_native_splash: ^2.3.1
  fluttertoast: ^8.2.2
  google_mlkit_text_recognition: ^0.8.1
  grpc: ^3.2.2
  hooks_riverpod: ^2.3.6
  lucide_icons: ^0.257.0
  package_info_plus: ^4.0.2
  path: ^1.8.3
  path_provider: ^2.0.15
  protobuf: ^3.0.0
  shared_preferences: ^2.1.2
  shimmer: ^3.0.0
  sqlite3_flutter_libs: ^0.5.14

dev_dependencies:
  build_runner: ^2.4.2
  custom_lint: ^0.4.0
  drift_dev: ^2.8.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  protoc_builder: ^0.4.0
  riverpod_lint: ^1.3.2

flutter:
  assets:
    - .env
    - assets/fonts/ZenKakuGothicNew/
  fonts:
    - family: ZenKakuGothicNew
      fonts:
        - asset: assets/fonts/ZenKakuGothicNew/ZenKakuGothicNew-Light.ttf
          weight: 300
        - asset: assets/fonts/ZenKakuGothicNew/ZenKakuGothicNew-Regular.ttf
          weight: 400
        - asset: assets/fonts/ZenKakuGothicNew/ZenKakuGothicNew-Medium.ttf
          weight: 500
        - asset: assets/fonts/ZenKakuGothicNew/ZenKakuGothicNew-Bold.ttf
          weight: 700
        - asset: assets/fonts/ZenKakuGothicNew/ZenKakuGothicNew-Black.ttf
          weight: 900
  uses-material-design: true

flutter_launcher_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  color: "#000000"
  image: "assets/icon/icon_text.png"
